### ISSUE TITLE
feat: vue-scoped-css/require-scoped to acknowledge `modules`

### ISSUE THREAD

**Issue by privatenumber** [future-architect/eslint-plugin-vue-scoped-css#101]
## Problem
A codebase I'm working in has a mix of scoped styles and CSS modules via `modules` attribute.

The `vue-scoped-css/require-scoped` warns on `<style module>`.

## Feature request
I understand this plugin is specifically for scoped CSS, and not CSS modules, but it would be nice if it can acknowledge that there is no violation when doing `<style module>`.

I'd like to be able to pass in `acceptModules` as an option to `vue-scoped-css/require-scoped`, so that it knows not to warn on styles scoped via CSS Modules.

-----

Amazing ESLint plugin as always!

**Comment by ota-meshi** [comment]
Thank you for suggesting a new option! Sounds good to me!
