### ISSUE TITLE
Ignore unused selector from regex.

### ISSUE THREAD

**Issue by gagagast** [future-architect/eslint-plugin-vue-scoped-css#233]
Hi.
Is there a way to ignore some selector to avoid false positive when we override selectors from some components library for example ?

**Comment by ota-meshi** [comment]
You can suppress those warnings using the `/* eslint-disable */` comment.
https://future-architect.github.io/eslint-plugin-vue-scoped-css/user-guide/#disabling-rules-via-eslint-disable

Or if that components library is BEM compliant and you want to ignore the modifier, you can use `ignoreBEMModifier` option.
https://future-architect.github.io/eslint-plugin-vue-scoped-css/rules/no-unused-selector.html#options

There is no way to ignore it with regexp.
I don't understand why it is needed. Can you give me a concrete example?

**Comment by ota-meshi** [comment]
There seems to be no progress. So close the issue.

**Comment by nagisaando** [comment]
I would like to open this issue again. I am having the same issue. 

I am using a component library (primeVue) and I need to modify the style of the component with the class name that primeVue has. They have a pattern for class name, and always has `p-` as prefix. (e.g.  .p-accordion, .p-card) However, those class names are internally implemented in primeVue, so eslint shows as error when I add css rules for those class.

 `captureClassesFromDoc` option looks to be a way to ignore those classes but that means I need to add the comment in every component file that is using primevue. Is there any way to ignore (with regex) in eslintrc file without adding `// eslint-disable-next-line vue-scoped-css/no-unused-selector` to every css rules?

**Comment by Hiroshiba** [comment]
@ota-meshi 
I also agree with this issue.
I'm using the [Quasar](https://quasar.dev/) library, and the internal classes have a prefix starting with `q-`.
As a result, I'd like to disable the `q-*` rules.
