### ISSUE TITLE
Issue with "ignoreBEMModifier" option for rule "no-unused-selector"

### ISSUE THREAD

**Issue by tsengorz** [future-architect/eslint-plugin-vue-scoped-css#27]
Hi, 

I notice that even with the "ignoreBEMModifier" set to true, the linter still consider the following an error,
```
<template>
  <div class="cool-component"></div>
</template>
<style scoped>
.cool-component {
  &--active { } // Linter error here.
}
</style>
```

Is this syntax not supported?

**Comment by ota-meshi** [comment]
Thank you for this issue.

You can give the parser the SCSS syntax by specifying "scss" in the "lang" attribute.

```vue
<template>
  <div class="cool-component"></div>
</template>
<style scoped lang="scss">
.cool-component {
  &--active { } // Linter error here.
}
</style>
```

You can check it in the [DEMO](https://future-architect.github.io/eslint-plugin-vue-scoped-css/playground/#eJxVj0FrwzAMhf+K8GGHUtf34uVQ6G39BfMOwdE6gysFyQmMkP8+pYWy3iTe0/ueFpd5QHd0seFtrH3DLhFAHMoMufaq78kcXH3m28iE1JLrYjDZfDH8O4qapYzNprAD1FqowTyh18wjDj6rBmI/0aS2KVbMjeUIn8mhCEtye1jKlVjwdL5ceCjfBU1vMuH6Bbuw4Z6IqO23IjyyofZ0tZ5qDGuX6PDaGJbtpTfv+9zKjLDACiHAhzVEgTsdflDwkGi9U7bszq1/EKdkeg==).

If you don't have the "lang" attribute, the parser will parse it as normal CSS.
To express nesting of concatenated strings in normal CSS, you need to add "@nest".

https://drafts.csswg.org/css-nesting/#at-nest

```vue
<template>
  <div class="cool-component"></div>
</template>
<style scoped>
.cool-component {
  @nest &--active { }
}
</style>
```

You can check it in the [DEMO](https://future-architect.github.io/eslint-plugin-vue-scoped-css/playground/#eJxVT80KwjAMfpXQgwex9i51iODRJ7AeRhelUJPRZAMZe3c7BdFbPr7fTCZyh2ZnvOKjz61iEwjAd2mEmFuRfagKzjbyo2dC0mAa7ypddd79mLzEknqtl1sDSk6kMA5oJXKPnY0ijtgONEhFghmjctnBJRgshUswG5jSnbjg8XQ+c5duCSuvZcD5Cmu31H0rvOgzI3yyK97+b4RpeeJAKAora9uoaUSYYA40v3MWd2PmF/h+WpU=).

**Comment by tsengorz** [comment]
@ota-meshi Thank you for the solution! I appreciate the fast response! 👍
