### ISSUE TITLE
it is not working for me 

### ISSUE THREAD

**Issue by zzzgit** [future-architect/eslint-plugin-vue-scoped-css#330]
I installed this plugin and then configured it in `eslint.config. js`. 

> [Info  - 8:07:14 PM] ESLint server is starting.
> [Info  - 8:07:14 PM] ESLint server running in node v18.15.0
> [Info  - 8:07:14 PM] ESLint server is running.
> [Info  - 8:07:14 PM] ESLint library loaded from: ~/project//node_modules/eslint/lib/api.js

```js
module.exports = {
	root: true,
	extends: [
		'...others',
		'plugin:vue/vue3-strongly-recommended',
		'plugin:vue-scoped-css/vue3-recommended'
	],
	plugins: [
		'vue',
	]
}
```
It is not working for me. Only the `script` section could be formatted but not the `style` section.

**Comment by ota-meshi** [comment]
I'm not sure what you mean. We cannot use `extends` or `root` in `eslint.config.js`.
Please provide the environment to reproduce the problem.

**Comment by zzzgit** [comment]
> I'm not sure what you mean. We cannot use `extends` or `root` in `eslint.config.js`. Please provide the environment to reproduce the problem.

Sorry, it's `.eslintrc.cjs`

**Comment by ota-meshi** [comment]
It works fine for me. Please create a minimally repository to reproduce the issue and share it with me.
